version: '2'
services:
  nginx:
    image: nginx:1.10
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - {{config_dir}}/nginx:/etc/nginx/conf.d:ro
       - {{config_dir}}/dehydrated:/etc/dehydrated:ro
    networks:
      - registry-net
    depends_on:
      - registry
      - registry-web
  registry-web:
    image: hyper/docker-registry-web:latest
    volumes:
       - {{config_dir}}/registry-web:/conf:ro
       - {{data_dir}}/web-db:/data
    networks:
      - registry-net
    depends_on:
       - registry
  registry:
    image: registry:2.4.1
    volumes:
      - {{config_dir}}/registry:/etc/docker/registry:ro
      - {{data_dir}}/registry:/var/lib/registry
    networks:
      - registry-net

networks:
  registry-net:
