version: '2'
services:
  nginx:
    image: nginx:1.10
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - ./nginx:/etc/nginx/conf.d:ro
       - ./dehydrated:/etc/dehydrated:ro
    networks:
      - registry-net
    depends_on:
      - registry
      - registry-web
  registry-web:
    image: hyper/docker-registry-web:latest
    volumes:
       - ./registry-web:/conf:ro
       - ../data/web-db:/data
    networks:
      - registry-net
    depends_on:
       - registry
  registry:
    image: registry:2.4.1
    volumes:
      - ./registry:/etc/docker/registry:ro
      - ../data/registry:/var/lib/registry
    networks:
      - registry-net

networks:
  registry-net:
